// Shared mock data for the Trading Cockpit prototypes.
// Lifted from /ux-mockups.html in the repo so all variations stay coherent.

window.COCKPIT_DATA = {
  cycle: {
    id: "C-14:32",
    asOf: "14:32 UTC",
    nextIn: "13 min",
    mode: "PAPER",
    submitEnabled: false,
    sourcesDegraded: 1,
    sourcesTotal: 7,
  },

  market: {
    regime: "balanced · risk-on tilt",
    spy20d: 2.4,
    vix: 14.8,
    breadth: 62,
    dispersion: 0.41,
    longThreshold: 0.56,
    sectorsTailwind: 4,
    sectorsPressure: 2,
    sectorsUnavail: 1,
  },

  engines: [
    { name: "Universe registry", state: "live", age: "6m" },
    { name: "Fundamentals", state: "live", age: "8m" },
    { name: "Market regime", state: "live", age: "2m" },
    { name: "Signals", state: "live", age: "1m" },
    { name: "Deterministic", state: "live", age: "4m" },
    { name: "LLM (gpt-5.4-mini)", state: "live", age: "4m" },
    { name: "Institutional 13F", state: "stale", age: "19h" },
  ],

  funnel: {
    universe: 152,
    universeReady: 150,
    fundamentalsPass: 47,
    fundamentalsWatch: 23,
    signals: 12,
    deterministic: 5,
    llmAgree: 3,
    final: 3,
    blockedByPolicy: 2,
  },

  // The 5 deterministic candidates from the mockup, plus a couple more
  // so 'Top 10' has weight. Convictions calibrated to the source doc.
  candidates: [
    {
      ticker: "NVDA",
      name: "NVIDIA Corp.",
      sector: "Technology",
      direction: "long",
      detConviction: 0.81,
      llmConviction: 0.74,
      finalConviction: 0.78,
      status: "approved",          // approved | blocked | demoted | rejected
      blocker: null,
      price: 815.40,
      qty: 12,
      notional: 9785,
      stopPct: -4.7,
      targetPct: 8.9,
      earningsDays: 24,
      evidence: [
        { tier: "confirmed", source: "SEC Form 4", text: "CFO bought 4,200 sh @ $812.40 on 2026-05-02" },
        { tier: "confirmed", source: "Sector ETF", text: "XLK +3.1% · breadth 9/10" },
        { tier: "confirmed", source: "Fundamentals", text: "Composite score 0.84 (profitability + cash)" },
      ],
      concerns: ["Valuation P/E at 90th percentile of sector"],
      llmRationale: "CFO insider buy is high-credibility. Tech sector tailwind validated by ETF + breadth. Sized conservatively at 8% (policy allows 14%) to leave room for valuation give-back.",
      gates: [
        { name: "Min conviction", val: "0.78 ≥ 0.62", ok: true },
        { name: "Position capacity", val: "7 / 10", ok: true },
        { name: "New positions / cycle", val: "1 / 3", ok: true },
        { name: "Sector exposure (Tech)", val: "22% ≤ 30%", ok: true },
        { name: "Single-name cap", val: "8% ≤ 25%", ok: true },
        { name: "Cash reserve", val: "18% ≥ 10%", ok: true },
      ],
    },
    {
      ticker: "HD",
      name: "Home Depot",
      sector: "Consumer Disc.",
      direction: "long",
      detConviction: 0.69,
      llmConviction: 0.66,
      finalConviction: 0.69,
      status: "approved",
      blocker: null,
      price: 384.20,
      qty: 12,
      notional: 4610,
      stopPct: -5.2,
      targetPct: 9.8,
      earningsDays: 31,
      evidence: [
        { tier: "confirmed", source: "Sector ETF", text: "XLY breadth held despite weak retail headline" },
        { tier: "confirmed", source: "Technical", text: "Breakout above 50d resistance on rising vol" },
        { tier: "inferred", source: "Options flow", text: "Net call premium 2.1× 30d avg" },
      ],
      concerns: ["Consumer discretionary breadth thin"],
      llmRationale: "Setup is technically clean. Sector mixed but breadth carries it. Position size 7%; would size larger if XLY tailwind broadens.",
      gates: [
        { name: "Min conviction", val: "0.69 ≥ 0.62", ok: true },
        { name: "Position capacity", val: "8 / 10", ok: true },
        { name: "Sector exposure (Disc.)", val: "11% ≤ 30%", ok: true },
        { name: "Cash reserve", val: "18% ≥ 10%", ok: true },
      ],
    },
    {
      ticker: "UNH",
      name: "UnitedHealth",
      sector: "Health Care",
      direction: "long",
      detConviction: 0.65,
      llmConviction: 0.62,
      finalConviction: 0.65,
      status: "approved",
      blocker: null,
      price: 544.10,
      qty: 8,
      notional: 4353,
      stopPct: -4.5,
      targetPct: 8.0,
      earningsDays: 18,
      evidence: [
        { tier: "confirmed", source: "Fundamentals", text: "Composite 0.71 · stable margins" },
        { tier: "confirmed", source: "Sector ETF", text: "XLV +0.9% · breadth 5/8" },
      ],
      concerns: ["Single corroborating lane (thin evidence breadth)", "Approaching 84% gross post-trade"],
      llmRationale: "At minimum conviction. No insider/news corroboration. Setup is acceptable but I would not enter a second healthcare name this cycle.",
      gates: [
        { name: "Min conviction", val: "0.65 ≥ 0.62", ok: true },
        { name: "Position capacity", val: "9 / 10", ok: true },
        { name: "Sector exposure (Health)", val: "9% ≤ 30%", ok: true },
        { name: "Gross post-trade", val: "84% ≤ 100%", ok: true, warn: true },
      ],
    },
    {
      ticker: "AVGO",
      name: "Broadcom Inc.",
      sector: "Technology",
      direction: "long",
      detConviction: 0.66,
      llmConviction: 0.38,
      finalConviction: 0.38,
      status: "demoted",
      blocker: "Earnings in 6 days — LLM demoted to WATCH",
      price: 1342.10,
      qty: 0,
      notional: 0,
      stopPct: null,
      targetPct: null,
      earningsDays: 6,
      evidence: [
        { tier: "confirmed", source: "SA Premium", text: "Quant rank Hold → Buy on 2026-05-05" },
        { tier: "inferred", source: "Options flow", text: "Net call premium 1.4× 30d avg" },
      ],
      concerns: ["Earnings in 6 days", "Score gap thin (0.12)"],
      llmRationale: "Deterministic + LLM disagree. Earnings event 6 days out — position risk too high to enter here. Revisit after earnings clear.",
      gates: [],
    },
    {
      ticker: "JPM",
      name: "JPMorgan Chase",
      sector: "Financials",
      direction: "long",
      detConviction: 0.71,
      llmConviction: 0.68,
      finalConviction: 0.71,
      status: "blocked",
      blocker: "Sector exposure cap reached (Financials 30% = 30%)",
      price: 198.40,
      qty: 0,
      notional: 0,
      stopPct: null,
      targetPct: null,
      earningsDays: 42,
      evidence: [
        { tier: "confirmed", source: "Fundamentals", text: "Composite 0.78 · ROE strong" },
        { tier: "confirmed", source: "Technical", text: "Higher highs on rising vol" },
      ],
      concerns: ["Financials sector at exposure cap"],
      llmRationale: "Setup is clean but portfolio already at cap. Would require reducing an existing Financials position to make room.",
      gates: [
        { name: "Min conviction", val: "0.71 ≥ 0.62", ok: true },
        { name: "Sector exposure (Fin.)", val: "30% = 30% (cap)", ok: false },
      ],
    },
    {
      ticker: "AAPL",
      name: "Apple Inc.",
      sector: "Technology",
      direction: "long",
      detConviction: 0.58,
      llmConviction: 0.55,
      finalConviction: 0.58,
      status: "rejected",
      blocker: "Below long threshold (0.56) by margin · evidence breadth = 1",
      price: 178.30,
      qty: 0,
      notional: 0,
      stopPct: null,
      targetPct: null,
      earningsDays: 27,
      evidence: [
        { tier: "confirmed", source: "Fundamentals", text: "Composite 0.66" },
      ],
      concerns: ["Only one corroborating lane"],
      llmRationale: "Thin evidence. No-trade.",
      gates: [],
    },
    {
      ticker: "MSFT",
      name: "Microsoft Corp.",
      sector: "Technology",
      direction: "long",
      detConviction: 0.54,
      llmConviction: 0.51,
      finalConviction: 0.54,
      status: "rejected",
      blocker: "Below long threshold (0.56)",
      price: 412.80,
      qty: 0,
      notional: 0,
      stopPct: null,
      targetPct: null,
      earningsDays: 9,
      evidence: [
        { tier: "confirmed", source: "Fundamentals", text: "Composite 0.62" },
        { tier: "inferred", source: "Options flow", text: "Mixed; neutral premium" },
      ],
      concerns: ["Earnings risk inside 14d window"],
      llmRationale: "Below threshold. Wait for cleaner setup post-earnings.",
      gates: [],
    },
    {
      ticker: "META",
      name: "Meta Platforms",
      sector: "Communications",
      direction: "long",
      detConviction: 0.49,
      llmConviction: 0.47,
      finalConviction: 0.49,
      status: "rejected",
      blocker: "Below long threshold (0.56)",
      price: 488.20,
      qty: 0,
      notional: 0,
      stopPct: null,
      targetPct: null,
      earningsDays: 15,
      evidence: [
        { tier: "confirmed", source: "Sector ETF", text: "XLC +2.4% · breadth 7/9" },
      ],
      concerns: [],
      llmRationale: "Sector tailwind only — not enough.",
      gates: [],
    },
    {
      ticker: "TSLA",
      name: "Tesla Inc.",
      sector: "Consumer Disc.",
      direction: "long",
      detConviction: 0.44,
      llmConviction: 0.40,
      finalConviction: 0.44,
      status: "rejected",
      blocker: "Inferred-only evidence (no confirmed corroboration)",
      price: 184.60,
      qty: 0,
      notional: 0,
      stopPct: null,
      targetPct: null,
      earningsDays: 11,
      evidence: [
        { tier: "inferred", source: "Volume bars", text: "3.2× average volume" },
      ],
      concerns: ["No confirmed evidence"],
      llmRationale: "Inferred bars only. No-trade.",
      gates: [],
    },
    {
      ticker: "NFLX",
      name: "Netflix Inc.",
      sector: "Communications",
      direction: "long",
      detConviction: 0.41,
      llmConviction: 0.39,
      finalConviction: 0.41,
      status: "rejected",
      blocker: "Evidence breadth fell below 2 (news relevance downgraded 0.41 → 0.31)",
      price: 612.80,
      qty: 0,
      notional: 0,
      stopPct: null,
      targetPct: null,
      earningsDays: 33,
      evidence: [],
      concerns: ["Disappeared mid-cycle"],
      llmRationale: "Removed at 14:30 when news relevance recomputed.",
      gates: [],
    },
  ],

  positions: [
    {
      ticker: "AAPL", entered: "2026-04-22", entry: 172.40, current: 178.30,
      stop: 163.80, target: 187.90, daysHeld: 14, status: "hold",
      thesis: "Setup aligned · stop intact · no regime risk",
    },
    {
      ticker: "MSFT", entered: "2026-04-19", entry: 405.10, current: 412.80,
      stop: 386.20, target: 442.00, daysHeld: 17, status: "hold",
      thesis: "Setup aligned · stop and target intact",
    },
    {
      ticker: "META", entered: "2026-04-15", entry: 482.40, current: 487.70,
      stop: 459.20, target: 525.80, daysHeld: 21, status: "review",
      thesis: "Evidence breadth fell to 1 · monitor next cycle",
    },
    {
      ticker: "HD", entered: "2026-04-10", entry: 386.10, current: 384.50,
      stop: 367.00, target: 419.00, daysHeld: 26, status: "review",
      thesis: "Mixed evidence · sector tailwind softer",
    },
    {
      ticker: "XOM", entered: "2026-04-08", entry: 113.40, current: 110.80,
      stop: 108.00, target: 122.50, daysHeld: 28, status: "close",
      thesis: "Setup flipped to NO_TRADE · Energy pressure now active",
    },
  ],

  account: {
    grossExposure: 67,
    grossPostTrade: 84,
    grossCap: 100,
    cashAvailable: 18,
    cashCap: 10,
    largestName: 14,
    largestNameCap: 25,
    openOrders: 2,
    openOrdersCap: 5,
    buyingPower: 28000,
    weekPnl: 0.7,
    weekTarget: 3.0,
  },

  sectors: [
    { name: "Technology",       state: "tailwind",  detail: "XLK +3.1% · 9/10" },
    { name: "Communications",   state: "tailwind",  detail: "XLC +2.4% · 7/9" },
    { name: "Industrials",      state: "tailwind",  detail: "XLI +1.6% · 6/8" },
    { name: "Health Care",      state: "tailwind",  detail: "XLV +0.9% · 5/8" },
    { name: "Cons. Staples",    state: "tailwind",  detail: "XLP +0.6%" },
    { name: "Financials",       state: "neutral",   detail: "XLF flat" },
    { name: "Utilities",        state: "neutral",   detail: "XLU mixed" },
    { name: "Cons. Disc.",      state: "neutral",   detail: "XLY -0.4%" },
    { name: "Energy",           state: "pressure",  detail: "XLE -2.1%" },
    { name: "Materials",        state: "pressure",  detail: "XLB -1.8%" },
    { name: "Real Estate",      state: "unavail",   detail: "XLRE degraded" },
  ],

  // ─── data sources (Universe panel) ──────────────────────────────
  sources: [
    { name: "SEC EDGAR · Company Facts", tier: "official", state: "fresh", lastPull: "2026-05-06 14:24", coverage: "150/150", note: "" },
    { name: "SEC EDGAR · Form 4 (insider)", tier: "official", state: "fresh", lastPull: "2026-05-06 14:25", coverage: "150/150", note: "" },
    { name: "SEC EDGAR · 13F (institutional)", tier: "official", state: "stale", lastPull: "2026-05-05 19:11", coverage: "104/150", note: "last filing season ended; refresh due 2026-05-15" },
    { name: "yfinance · daily bars", tier: "market", state: "fresh", lastPull: "2026-05-06 14:30", coverage: "150/150", note: "" },
    { name: "Alpaca · paper account", tier: "broker", state: "fresh", lastPull: "2026-05-06 14:31", coverage: "—", note: "buying power $28k · 5 positions" },
    { name: "Sector ETFs (XL*)", tier: "market", state: "partial", lastPull: "2026-05-06 14:29", coverage: "10/11", note: "XLRE intermittent" },
    { name: "SA Premium · email digest", tier: "paid-sub", state: "fresh", lastPull: "2026-05-06 14:07", coverage: "1 digest", note: "3 confirmed events extracted" },
    { name: "Google News · RSS", tier: "rss", state: "fresh", lastPull: "2026-05-06 14:28", coverage: "—", note: "6 items → 1 passed relevance gate" },
    { name: "OpenAI · gpt-5.4-mini", tier: "llm", state: "fresh", lastPull: "2026-05-06 14:30", coverage: "5/5 candidates reviewed", note: "prompt v2.1" },
  ],

  universeBlocked: [
    { ticker: "XYZ", reason: "Missing CIK in SEC mapping", action: "Re-pull SEC ticker map", attempted: "14:25" },
    { ticker: "ABC", reason: "SEC fundamentals unavailable", action: "Wait for next filing (est. 2026-05-15)", attempted: "14:25" },
  ],

  // ─── signals (Signals panel) ────────────────────────────────────
  signals: [
    { ticker: "NVDA", kind: "Insider buying",    tier: "confirmed", source: "SEC Form 4",     impact: "high",   note: "CFO bought 4,200 sh @ $812.40 · filed 2026-05-04" },
    { ticker: "AVGO", kind: "Quant rank upgrade", tier: "confirmed", source: "SA Premium",     impact: "high",   note: "Hold → Buy on 2026-05-05" },
    { ticker: "HD",   kind: "Technical breakout", tier: "confirmed", source: "Bars",           impact: "med",    note: "Above 50d resistance on rising volume" },
    { ticker: "UNH",  kind: "Sector tailwind",    tier: "confirmed", source: "Sector ETF",     impact: "med",    note: "XLV +0.9% · breadth 5/8" },
    { ticker: "JPM",  kind: "Fundamentals shift", tier: "confirmed", source: "SEC Company Facts", impact: "high", note: "ROE re-rated · composite 0.78" },
    { ticker: "NVDA", kind: "Sector tailwind",    tier: "confirmed", source: "Sector ETF",     impact: "med",    note: "XLK +3.1% · breadth 9/10" },
    { ticker: "AVGO", kind: "Options flow",       tier: "inferred",  source: "Options chain",   impact: "med",    note: "Net call premium 1.4× 30d avg" },
    { ticker: "HD",   kind: "Options flow",       tier: "inferred",  source: "Options chain",   impact: "low",    note: "Net call premium 2.1× 30d avg" },
    { ticker: "TSLA", kind: "Abnormal volume",    tier: "inferred",  source: "Daily bars",     impact: "med",    note: "3.2× average volume; not a confirmed block trade" },
    { ticker: "META", kind: "Sector momentum",    tier: "inferred",  source: "Constituents",   impact: "low",    note: "Breadth 7/9" },
    { ticker: "NFLX", kind: "News article",       tier: "inferred",  source: "Google News",    impact: "low",    note: "Relevance recomputed 0.41 → 0.31" },
    { ticker: "MSFT", kind: "Options flow",       tier: "inferred",  source: "Options chain",   impact: "low",    note: "Mixed; neutral premium" },
    { ticker: "META", kind: "News headline",      tier: "suppressed", source: "Google News",    impact: "—",      note: "Ticker-relevance 0.18 below 0.35 floor" },
    { ticker: "AAPL", kind: "Forum chatter",       tier: "suppressed", source: "RSS",            impact: "—",      note: "Tier=RSS-headline · not enough signal" },
    { ticker: "XOM",  kind: "Sector pressure",     tier: "confirmed", source: "Sector ETF",     impact: "high",   note: "XLE -2.1% · sector flipped to pressure", negative: true },
  ],

  // ─── audit trace (NFLX disappearance from final selection) ──────
  auditLifecycle: {
    NFLX: {
      title: "Why NFLX disappeared at 14:30",
      summary: "Was a candidate at 14:22. Removed when news relevance recomputed: 0.41 → 0.31, dropping confirmed-evidence count below the breadth-of-2 floor.",
      events: [
        { t: "14:08", state: "entered universe", note: "SP100 + QQQ membership" },
        { t: "14:14", state: "passed fundamentals", note: "composite 0.71" },
        { t: "14:18", state: "signal fresh", note: "positive news article (relevance 0.41)" },
        { t: "14:22", state: "deterministic long 0.62", note: "at threshold; evidence breadth = 2" },
        { t: "14:25", state: "LLM reviewed", note: "watch · 0.55 — said 'thin breadth, single news lane'" },
        { t: "14:28", state: "news relevance recomputed", note: "0.41 → 0.31 (article title parsed; secondary mention)", critical: true },
        { t: "14:30", state: "removed", note: "evidence breadth fell to 1 · below floor of 2", critical: true },
      ],
    },
  },

  // ─── policy (Policy panel) ──────────────────────────────────────
  policy: {
    convictionGates: [
      { key: "long_threshold",     label: "Long threshold (det.)",        v: 0.56, min: 0.40, max: 0.80, step: 0.01, unit: "" },
      { key: "min_final_conv",     label: "Min final conviction",         v: 0.62, min: 0.50, max: 0.80, step: 0.01, unit: "" },
      { key: "agreement_bonus",    label: "Det.+LLM agreement bonus",     v: 0.07, min: 0,    max: 0.15, step: 0.01, unit: "" },
      { key: "evidence_breadth",   label: "Min evidence breadth",         v: 2,    min: 1,    max: 4,    step: 1,    unit: " lanes" },
    ],
    portfolioCaps: [
      { key: "gross_cap",          label: "Gross exposure cap",           v: 100,  min: 50,   max: 150,  step: 5,    unit: "%" },
      { key: "cash_floor",         label: "Cash reserve floor",           v: 10,   min: 5,    max: 30,   step: 1,    unit: "%" },
      { key: "sector_cap",         label: "Per-sector cap",               v: 30,   min: 15,   max: 50,   step: 1,    unit: "%" },
      { key: "single_name_cap",    label: "Single-name cap",              v: 25,   min: 5,    max: 40,   step: 1,    unit: "%" },
      { key: "max_positions",      label: "Max open positions",           v: 10,   min: 3,    max: 20,   step: 1,    unit: "" },
      { key: "new_per_cycle",      label: "New positions per cycle",      v: 3,    min: 1,    max: 6,    step: 1,    unit: "" },
    ],
    flags: [
      { key: "BROKER_SUBMIT_ENABLED", label: "Allow paper submit",        v: true,  danger: false },
      { key: "SHORTS_ENABLED",        label: "Allow short positions",      v: false, danger: true },
      { key: "LIVE_TRADING",          label: "Live (real money)",         v: false, danger: true, locked: true },
      { key: "BRACKET_ORDERS",        label: "Auto-attach OCO brackets",  v: true,  danger: false },
      { key: "LLM_REVIEW",            label: "Require LLM review",        v: true,  danger: false },
    ],
  },

  // ─── monitor (between-cycle event stream) ───────────────────────
  monitorEvents: [
    { t: "14:31:08", sev: "info",   topic: "cycle",      msg: "Cycle C-14:32 boundary — refresh begins" },
    { t: "14:30:42", sev: "warn",   topic: "candidate",  msg: "NFLX evidence breadth fell to 1 · removed from final selection" },
    { t: "14:29:55", sev: "info",   topic: "signal",     msg: "News article re-scored: NFLX relevance 0.41 → 0.31" },
    { t: "14:28:11", sev: "warn",   topic: "source",     msg: "13F refresh skipped — last filing season ended (next 2026-05-15)" },
    { t: "14:27:30", sev: "info",   topic: "candidate",  msg: "AVGO demoted by LLM (earnings 6d) — staged as WATCH" },
    { t: "14:26:02", sev: "info",   topic: "signal",     msg: "NVDA Form 4 confirmed: CFO bought 4,200 sh" },
    { t: "14:24:11", sev: "info",   topic: "source",     msg: "SEC EDGAR Company Facts refresh complete · 150/150" },
    { t: "14:22:48", sev: "block",  topic: "policy",     msg: "JPM blocked: Financials sector exposure at 30% cap" },
    { t: "14:19:33", sev: "info",   topic: "regime",     msg: "Macro: balanced · no regime change in 8 cycles" },
    { t: "14:18:09", sev: "warn",   topic: "source",     msg: "XLRE feed intermittent — sector marked unavailable" },
    { t: "14:14:55", sev: "info",   topic: "candidate",  msg: "47 of 150 passed fundamentals (composite ≥ 0.50)" },
    { t: "14:08:02", sev: "info",   topic: "cycle",      msg: "Cycle C-14:08 begins — universe of 150 tickers" },
  ],
};
